# Generated by Django 5.2 on 2025-07-04 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marhala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='books/')),
                ('marhala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marhala')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='notes/')),
                ('marhala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marhala')),
            ],
        ),
        migrations.AddField(
            model_name='marhala',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
    ]
